
const KEY='seatrip_app_v1';
const defaults={boats:[
        {id:"boat-galini", name:"Γαλήνη", cruiseSpeed:20, maxSpeed:30, fuelCruise:10, fuelMax:18, fuelTank:25, oilTank:2, oilRatio:0.02},
        {id:"boat-rib-620", name:"Φουσκωτό 6.2m 120HP", cruiseSpeed:24, maxSpeed:38, fuelCruise:24, fuelMax:42, fuelTank:140, oilTank:0, oilRatio:0},
        {id:"boat-rafnar-1200", name:"Rafnar 1200 T-Top", cruiseSpeed:32, maxSpeed:50, fuelCruise:128, fuelMax:190, fuelTank:900, oilTank:0, oilRatio:0},
        {id:"boat-technohull-38", name:"Technohull 38 Grand Sport", cruiseSpeed:35, maxSpeed:73, fuelCruise:60, fuelMax:160, fuelTank:600, oilTank:0, oilRatio:0},
        {id:"boat-technohull-alpha-50", name:"Technohull Alpha 50", cruiseSpeed:55, maxSpeed:86, fuelCruise:320, fuelMax:500, fuelTank:1800, oilTank:0, oilRatio:0},
        {id:"boat-hnc-660", name:"Hnc 660 140hp (Ενοικίαση)", cruiseSpeed:32, maxSpeed:40, fuelCruise:30, fuelMax:55, fuelTank:150, oilTank:0, oilRatio:0},
        {id:"boat-saxdor-320", name:"Saxdor 320 GTO", cruiseSpeed:24.7, maxSpeed:52.5, fuelCruise:56, fuelMax:120, fuelTank:428, oilTank:0, oilRatio:0},
        {id:"boat-saxdor-400", name:"Saxdor 400 GTO", cruiseSpeed:35, maxSpeed:45, fuelCruise:140, fuelMax:220, fuelTank:1000, oilTank:0, oilRatio:0}
      ],routes:[
        {id:"route-mati-evia", name:"Μάτι - Εύβοια", distance:12.5, notes:"Αρχικά: 10 με 15"},
        {id:"route-mati-sounio", name:"Μάτι - Σούνιο", distance:26, notes:""},
        {id:"route-mati-lavrio", name:"Μάτι - Λαύριο", distance:23, notes:""},
        {id:"route-mati-makronisos", name:"Μάτι - Μακρόνησος", distance:23, notes:""},
        {id:"route-mati-kea", name:"Μάτι - Κέα", distance:30, notes:""},
        {id:"route-kea-polyegos", name:"Κέα - Πολύεγος", distance:56, notes:""},
        {id:"route-mati-andros", name:"Μάτι - Άνδρος", distance:45, notes:"Αρχικά: 35 με 55"},
        {id:"route-anavyssos-paros", name:"Ανάβυσσος - Πάρος", distance:75, notes:""},
        {id:"route-anavyssos-kea", name:"Ανάβυσσος - Κέα", distance:23, notes:""},
        {id:"route-anavyssos-kythnos", name:"Ανάβυσσος - Κύθνος", distance:33, notes:""},
        {id:"route-anavyssos-koufonisia", name:"Ανάβυσσος - Κουφονήσια", distance:110, notes:""},
        {id:"route-faliro-polyegos", name:"Φάληρο - Πολύεγος", distance:85, notes:""},
        {id:"route-faliro-ydra", name:"Φάληρο - Ύδρα", distance:36, notes:""},
        {id:"route-faliro-sounio", name:"Φάληρο - Σούνιο", distance:25, notes:""},
        {id:"route-faliro-kythnos", name:"Φάληρο - Κύθνος", distance:47, notes:""},
        {id:"route-faliro-aegina", name:"Φάληρο - Αίγινα", distance:15.5, notes:"Αρχικά: 13 με 18"},
        {id:"route-faliro-paros", name:"Φάληρο - Πάρος", distance:90, notes:""},
        {id:"route-faliro-agios-nikolaos", name:"Φάληρο - Άγιος Νικόλαος", distance:170, notes:""},
        {id:"route-faliro-siteia", name:"Φάληρο - Σητεία", distance:170, notes:""},
        {id:"route-faliro-gavdos", name:"Φάληρο - Γαύδος", distance:200, notes:""},
        {id:"route-faliro-heraklion", name:"Φάληρο - Ηράκλειο", distance:170, notes:""},
        {id:"route-faliro-chania", name:"Φάληρο - Χανιά", distance:150, notes:""},
        {id:"route-faliro-santorini", name:"Φάληρο - Σαντορίνη", distance:125, notes:""}
      ],rentals:[
{id:'rb1',name:'HNC 660 140hp',day:280,cruiseSpeed:32,maxSpeed:40,fuelCruise:30,fuelMax:55,fuelTank:150,oilRatio:0,selected:true},
{id:'rb2',name:'Saxdor 320 GTO',day:950,cruiseSpeed:24.7,maxSpeed:52.5,fuelCruise:56,fuelMax:120,fuelTank:428,oilRatio:0,selected:true},
{id:'rb3',name:'Technohull 38 GS',day:1200,cruiseSpeed:35,maxSpeed:73,fuelCruise:60,fuelMax:160,fuelTank:600,oilRatio:0,selected:true}
],trips:[],settings:{fuelPrice:2,oilPrice:15,safety:10,tripType:'1',rentDays:1,rentProfile:'balanced',w:{cost:30,time:20,fuel:15,range:15,speed:10,tank:10}},links:[{title:'Υπολογισμός αποστάσεων',url:'https://map.openseamap.org/',note:'OpenSeaMap για χάρτη και διαδρομές'},{title:'Καιρός / κύματα',url:'https://www.windy.com/-Waves-waves?waves,38.065,24.583,6',note:'Windy waves και άνεμος'},{title:'Ναυτικοί χάρτες',url:'https://maps.garmin.com/en-US/marine/?maps=another-brand&overlay=false&key=sw9pc6q5058p',note:'Garmin marine chart viewer'}]};
const DATA_URL='./data.json';
let state=structuredClone(defaults), lastTrip=null; const $=id=>document.getElementById(id); const $$=s=>[...document.querySelectorAll(s)];
const clone=o=>JSON.parse(JSON.stringify(o));
function normalizeData(data){let base=clone(defaults), d=data||{};return {...base,...d,boats:Array.isArray(d.boats)?d.boats:base.boats,routes:Array.isArray(d.routes)?d.routes:base.routes,rentals:Array.isArray(d.rentals)?d.rentals:base.rentals,trips:Array.isArray(d.trips)?d.trips:base.trips,settings:{...base.settings,...(d.settings||{}),w:{...base.settings.w,...((d.settings||{}).w||{})}},links:Array.isArray(d.links)?d.links:base.links}}
function setDefaults(data){let next=normalizeData(data);Object.keys(defaults).forEach(k=>delete defaults[k]);Object.assign(defaults,next)}
async function loadDataJson(show=false,overwriteLocal=false){try{let res=await fetch(DATA_URL+'?v='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);let data=await res.json();setDefaults(data);if(overwriteLocal){localStorage.removeItem(KEY);state=clone(defaults);save();render()}if(show)toast('✓ data.json');return true}catch(e){console.warn('data.json not loaded',e);if(show)toast('Δεν φορτώθηκε το data.json');return false}}
function load(){try{let saved=JSON.parse(localStorage.getItem(KEY)||'{}'), base=clone(defaults); return {...base,...saved,settings:{...base.settings,...(saved.settings||{}),w:{...base.settings.w,...((saved.settings||{}).w||{})}},links:saved.links||base.links}}catch{return clone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));counts()} function id(p){return p+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function num(v,d=0){const x=Number(String(v).replace(',','.'));return Number.isFinite(x)?x:d} function fmt(x,d=1){return Number.isFinite(x)?x.toLocaleString('el-GR',{maximumFractionDigits:d,minimumFractionDigits:d}):'—'} function eur(x){return Number.isFinite(x)?x.toLocaleString('el-GR',{style:'currency',currency:'EUR'}):'—'} function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){$('toast').textContent=t;$('toast').classList.add('on');clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').classList.remove('on'),1800)}
function counts(){$('boatCount').textContent=state.boats.length;$('tripCount').textContent=state.routes.length;$('rentCount').textContent=state.rentals.length}
function fillSelect(el,arr){$(el).innerHTML=arr.map(x=>`<option value="${x.id}">${esc(x.name)}${x.distance?' · '+fmt(x.distance)+' nm':''}</option>`).join('')}
function render(){counts();fillSelect('calcBoat',state.boats);fillSelect('calcRoute',state.routes);fillSelect('rentRoute',state.routes);$('fuelPrice').value=state.settings.fuelPrice;$('oilPrice').value=state.settings.oilPrice;$('safety').value=state.settings.safety;$('tripType').value=state.settings.tripType;$('rentFuelPrice').value=state.settings.fuelPrice;$('rentOilPrice').value=state.settings.oilPrice;$('rentSafety').value=state.settings.safety;$('rentTripType').value=state.settings.tripType;$('rentDays').value=state.settings.rentDays;$('rentProfile').value=state.settings.rentProfile||'balanced';Object.entries(state.settings.w).forEach(([k,v])=>{let el=$('w'+k[0].toUpperCase()+k.slice(1)); if(el)el.value=v});applyProfile(false);syncDistance();syncRentDistance();renderBoats();renderRoutes();renderRentals();renderLinks();calculate();rankRentals()}
function route(sel){return state.routes.find(r=>r.id===$(sel).value)||state.routes[0]} function boat(sel){return state.boats.find(b=>b.id===$(sel).value)||state.boats[0]}
function syncDistance(){let r=route('calcRoute'); if(r)$('distance').value=r.distance} function syncRentDistance(){let r=route('rentRoute'); if(r)$('rentDistance').value=r.distance}
function calc(distance,b,fp,op,safety,type=1,mode='cruise'){distance*=type;let sp=mode==='max'?b.maxSpeed:b.cruiseSpeed,lph=mode==='max'?b.fuelMax:b.fuelCruise;let h=sp>0?distance/sp:NaN;let fuel=h*lph;let fuelSafe=fuel*(1+safety/100);let oil=fuelSafe*(b.oilRatio||0);let cost=fuelSafe*fp+oil*op;let range=b.fuelCruise>0?b.fuelTank/(b.fuelCruise/b.cruiseSpeed):0;let margin=range?range-distance:0;let tankPct=b.fuelTank>0?(fuelSafe/b.fuelTank*100):NaN;return{distance,h,min:h*60,fuel,fuelSafe,oil,cost,sp,lph,range,margin,lpnm:fuelSafe/distance,tankPct}}
function metric(k,v,main=''){return`<div class="metric ${main}"><small>${k}</small><b>${v}</b></div>`}
function resultCard(title,r,best){return`<article class="card ${best?'best':''}"><div class="cardTop"><div class="name">${title}</div>${best?'<div class="pill">best</div>':''}</div><div class="metrics">${metric('€',eur(r.cost),'main')}${metric('ώρα',fmt(r.h,2)+' h','main')}${metric('L',fmt(r.fuelSafe,1))}${metric('L/nm',fmt(r.lpnm,2))}${metric('δοχείο',fmt(r.tankPct,1)+'%')}${metric('range',fmt(r.range,0)+' nm')}${metric('margin',fmt(r.margin,0)+' nm')}</div></article>`}
function calculate(){let b=boat('calcBoat'),dist=num($('distance').value),fp=num($('fuelPrice').value,2),op=num($('oilPrice').value,15),s=num($('safety').value,10),t=num($('tripType').value,1);state.settings={...state.settings,fuelPrice:fp,oilPrice:op,safety:s,tripType:String(t)};let c=calc(dist,b,fp,op,s,t,'cruise'),m=calc(dist,b,fp,op,s,t,'max');lastTrip={boat:b.name,route:route('calcRoute').name,distance:dist*t,cruise:c,max:m,at:new Date().toISOString()};$('results').innerHTML=resultCard('Cruise',c,c.cost<=m.cost)+resultCard('Max',m,m.cost<c.cost);save()}
function renderRoutes(){let list=$('routesList'); if(!list)return; list.innerHTML=state.routes.length?state.routes.map(r=>`<div class="row"><div><b>${esc(r.name)}</b><div class="mini">${fmt(r.distance)} nm${r.notes?' · '+esc(r.notes):''}</div></div><div class="hideMob">${fmt(r.distance)} nm</div><div class="hideMob">${esc(r.notes||'')}</div><div class="actions"><button class="btn soft" onclick="editRoute('${r.id}')">✎</button><button class="btn bad" onclick="deleteRoute('${r.id}')">×</button></div></div>`).join(''):'<div class="empty">—</div>'}
function readRoute(){return{name:$('routeName').value||'Προορισμός',distance:num($('routeDistance').value),notes:$('routeNotes').value||''}}
$('saveRouteBtn').onclick=()=>{let r=readRoute(),rid=$('routeId').value;if(rid){state.routes=state.routes.map(x=>x.id===rid?{...x,...r}:x)}else state.routes.push({id:id('r'),...r});$('routeId').value='';save();render();toast('✓')}
$('newRouteBtn').onclick=()=>{['routeId','routeName','routeDistance','routeNotes'].forEach(x=>$(x).value='')}
window.editRoute=rid=>{let r=state.routes.find(x=>x.id===rid); if(!r)return; $('routeId').value=r.id;$('routeName').value=r.name;$('routeDistance').value=r.distance;$('routeNotes').value=r.notes||'';toast('✎')}
window.deleteRoute=rid=>{state.routes=state.routes.filter(x=>x.id!==rid);save();render()}
function renderBoats(){let list=$('boatsList');list.innerHTML=state.boats.map(b=>`<div class="row"><div><b>${esc(b.name)}</b><div class="mini">${fmt(b.cruiseSpeed)} kn · ${fmt(b.fuelCruise)} L/h · ${fmt(b.fuelTank,0)} L</div></div><div class="hideMob">${fmt(b.maxSpeed)} kn</div><div class="hideMob">${fmt(b.fuelMax)} L/h</div><div class="actions"><button class="btn soft" onclick="editBoat('${b.id}')">✎</button><button class="btn bad" onclick="deleteBoat('${b.id}')">×</button></div></div>`).join('')}
function readBoat(){return{name:$('boatName').value||'Boat',cruiseSpeed:num($('cruiseSpeed').value),maxSpeed:num($('maxSpeed').value),fuelCruise:num($('fuelCruise').value),fuelMax:num($('fuelMax').value),fuelTank:num($('fuelTank').value),oilRatio:num($('oilRatio').value)}}
$('saveBoatBtn').onclick=()=>{let b=readBoat(),bid=$('boatId').value;if(bid){state.boats=state.boats.map(x=>x.id===bid?{...x,...b}:x)}else state.boats.push({id:id('b'),...b});$('boatId').value='';save();render();toast('✓')}
$('newBoatBtn').onclick=()=>{['boatId','boatName','cruiseSpeed','maxSpeed','fuelCruise','fuelMax','fuelTank','oilRatio'].forEach(x=>$(x).value='')}
window.editBoat=bid=>{let b=state.boats.find(x=>x.id===bid);$('boatId').value=b.id;$('boatName').value=b.name;$('cruiseSpeed').value=b.cruiseSpeed;$('maxSpeed').value=b.maxSpeed;$('fuelCruise').value=b.fuelCruise;$('fuelMax').value=b.fuelMax;$('fuelTank').value=b.fuelTank;$('oilRatio').value=b.oilRatio||0;toast('✎')}
window.deleteBoat=bid=>{state.boats=state.boats.filter(x=>x.id!==bid);save();render()}
function renderRentals(){let list=$('rentalList');list.innerHTML=state.rentals.map(b=>`<div class="row rental"><label class="check"><input type="checkbox" ${b.selected?'checked':''} onchange="toggleRent('${b.id}',this.checked)"><span>${esc(b.name)}</span></label><div>${eur(b.day)}</div><div class="hideMob">${fmt(b.cruiseSpeed)} kn</div><div class="hideMob">${fmt(b.fuelCruise)} L/h</div><div class="actions"><button class="btn soft" onclick="editRent('${b.id}')">✎</button><button class="btn bad" onclick="deleteRent('${b.id}')">×</button></div></div>`).join('')}
window.toggleRent=(bid,on)=>{let b=state.rentals.find(x=>x.id===bid); if(b)b.selected=on; save(); rankRentals()}
function rentalFromForm(){return{name:$('rentName').value||'Rental',day:num($('rentDay').value),cruiseSpeed:num($('rentCruiseSpeed').value),maxSpeed:num($('rentMaxSpeed').value),fuelCruise:num($('rentFuelCruise').value),fuelMax:num($('rentFuelCruise').value)*1.7,fuelTank:num($('rentFuelTank').value),oilRatio:num($('rentOilRatio').value)}}
$('saveRentBoatBtn').onclick=()=>{let b=rentalFromForm(),bid=$('rentBoatId').value;if(bid)state.rentals=state.rentals.map(x=>x.id===bid?{...x,...b}:x);else state.rentals.push({id:id('rb'),selected:true,...b});$('rentBoatId').value='';save();render();toast('✓')}
$('newRentBtn').onclick=()=>{$$('input[id^=rent]').forEach(i=>{if(i.type!=='number'||!['rentFuelPrice','rentOilPrice','rentSafety','rentDays','rentDistance'].includes(i.id))i.value=''})}
window.editRent=bid=>{let b=state.rentals.find(x=>x.id===bid);$('rentBoatId').value=b.id;$('rentName').value=b.name;$('rentDay').value=b.day;$('rentCruiseSpeed').value=b.cruiseSpeed;$('rentMaxSpeed').value=b.maxSpeed;$('rentFuelCruise').value=b.fuelCruise;$('rentFuelTank').value=b.fuelTank;$('rentOilRatio').value=b.oilRatio||0}
window.deleteRent=bid=>{state.rentals=state.rentals.filter(x=>x.id!==bid);save();render()}

const profiles={price:{cost:65,time:10,fuel:10,range:5,speed:0,tank:10,hint:'Κερδίζει το πιο οικονομικό συνολικά: ενοικίαση + κόστος ταξιδιού.'},speed:{cost:10,time:45,fuel:5,range:5,speed:30,tank:5,hint:'Κερδίζει το πιο γρήγορο, με βάρος σε χρόνο και ταχύτητα.'},autonomy:{cost:10,time:5,fuel:10,range:45,speed:5,tank:25,hint:'Κερδίζει αυτό που έχει καλύτερη αυτονομία και χρησιμοποιεί μικρότερο μέρος του δοχείου.'},balanced:{cost:30,time:20,fuel:15,range:15,speed:10,tank:10,hint:'Ισορροπία τιμής, χρόνου, καυσίμου, αυτονομίας και ασφάλειας.'},custom:{hint:'Γράψε εσύ τα βάρη. Δεν χρειάζεται να αθροίζουν 100, κανονικοποιούνται αυτόματα.'}};
function applyProfile(write=true){let p=$('rentProfile')?.value||'balanced';state.settings.rentProfile=p;let pr=profiles[p]||profiles.balanced;$('profileHint').textContent=pr.hint;if(p!=='custom'){Object.entries(pr).forEach(([k,v])=>{let el=$('w'+k[0].toUpperCase()+k.slice(1));if(el&&k!=='hint')el.value=v});} if(write){save();rankRentals();}}
function renderLinks(){let el=$('usefulLinks'); if(!el)return; el.innerHTML=(state.links||defaults.links).map(l=>`<article class="linkcard"><b>${esc(l.title)}</b><div class="mini">${esc(l.note)}</div><a class="btn soft" href="${esc(l.url)}" target="_blank" rel="noopener">Άνοιγμα</a></article>`).join('')}
function measureNm(){let la=num($('latA').value,NaN),lo=num($('lonA').value,NaN),lb=num($('latB').value,NaN),lob=num($('lonB').value,NaN); if(![la,lo,lb,lob].every(Number.isFinite)){toast('Βάλε 4 συντεταγμένες');return;} let R=3440.065,toRad=x=>x*Math.PI/180,dLat=toRad(lb-la),dLon=toRad(lob-lo),a=Math.sin(dLat/2)**2+Math.cos(toRad(la))*Math.cos(toRad(lb))*Math.sin(dLon/2)**2,c=2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));$('nmResult').textContent=fmt(R*c,2)+' nm'}
function scoreItems(items,w){let keys={cost:'low',h:'low',lpnm:'low',range:'high',sp:'high',tankPct:'low'};return items.map(it=>{let score=0,total=0;Object.entries({cost:w.cost,h:w.time,lpnm:w.fuel,range:w.range,sp:w.speed,tankPct:w.tank}).forEach(([k,wt])=>{wt=num(wt); if(!wt)return; let vals=items.map(i=>i[k]).filter(Number.isFinite),min=Math.min(...vals),max=Math.max(...vals); let part=max===min?1:(keys[k]==='low'?(max-it[k])/(max-min):(it[k]-min)/(max-min));score+=part*wt;total+=wt});return{...it,score:total?Math.round(score/total*100):0}}).sort((a,b)=>b.score-a.score)}
function rankRentals(){let dist=num($('rentDistance').value),days=num($('rentDays').value,1),fp=num($('rentFuelPrice').value,2),op=num($('rentOilPrice').value,15),s=num($('rentSafety').value,10),t=num($('rentTripType').value,1);let w={cost:num($('wCost').value,30),time:num($('wTime').value,20),fuel:num($('wFuel').value,15),range:num($('wRange').value,15),speed:num($('wSpeed').value,10),tank:num($('wTank').value,10)};state.settings={...state.settings,fuelPrice:fp,oilPrice:op,safety:s,tripType:String(t),rentDays:days,rentProfile:$('rentProfile').value,w};let items=state.rentals.filter(b=>b.selected).map(b=>{let r=calc(dist,b,fp,op,s,t,'cruise');return{...b,...r,cost:r.cost+(b.day*days),tripCost:r.cost,rentalCost:b.day*days}});let ranked=scoreItems(items,w);$('rentResults').innerHTML=ranked.length?ranked.map((r,i)=>`<article class="card ${i===0?'best':''}"><div class="cardTop"><div><div class="name">${esc(r.name)}</div><div class="score">${r.score}</div></div>${i===0?'<div class="pill">best</div>':''}</div><div class="metrics">${metric('σύνολο',eur(r.cost),'main')}${metric('ενοικίαση',eur(r.rentalCost))}${metric('ταξίδι',eur(r.tripCost))}${metric('ώρα',fmt(r.h,2)+' h','main')}${metric('L/nm',fmt(r.lpnm,2))}${metric('δοχείο',fmt(r.tankPct,1)+'%')}${metric('range',fmt(r.range,0)+' nm')}${metric('margin',fmt(r.margin,0)+' nm')}${metric('kn',fmt(r.sp,1))}</div></article>`).join(''):'<div class="empty">—</div>';save()}
function csv(name,rows){let data=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv'}));a.download=name;a.click()}
$('exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='seatrip-backup.json';a.click()}
function exportBackup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='seatrip-backup.json';a.click()}
$('backupExportBtn').onclick=exportBackup;
$('backupImportFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let reader=new FileReader();reader.onload=()=>{try{let data=JSON.parse(reader.result);state=normalizeData(data);save();render();toast('✓ import')}catch(err){toast('Το JSON δεν φορτώθηκε')}};reader.readAsText(f)};
$('backupLoadDataBtn').onclick=()=>loadDataJson(true,true);
$('backupResetBtn').onclick=async()=>{if(confirm('Να φορτωθούν τα αρχικά σκάφη και οι αρχικοί προορισμοί; Θα αντικατασταθούν τα τωρινά τοπικά δεδομένα.')){let ok=await loadDataJson(false,false);localStorage.removeItem(KEY);state=clone(defaults);save();render();toast(ok?'✓ data.json':'✓ αρχικά δεδομένα')}}
$('calculateBtn').onclick=calculate;$('resetDistanceBtn').onclick=syncDistance;$('rankRentBtn').onclick=rankRentals;$('selectAllRentBtn').onclick=()=>{state.rentals.forEach(r=>r.selected=true);save();renderRentals();rankRentals()};$('rentRoute').onchange=()=>{syncRentDistance();rankRentals()};$('calcRoute').onchange=()=>{syncDistance();calculate()};['distance','fuelPrice','oilPrice','safety','tripType','calcBoat'].forEach(x=>$(x).addEventListener('input',calculate));['rentDistance','rentDays','rentFuelPrice','rentOilPrice','rentSafety','rentTripType','wCost','wTime','wFuel','wRange','wSpeed','wTank'].forEach(x=>$(x).addEventListener('input',rankRentals));
$('rentProfile').addEventListener('change',()=>applyProfile(true));
$$('.w').forEach(i=>i.addEventListener('input',()=>{if($('rentProfile').value!=='custom')$('rentProfile').value='custom';state.settings.rentProfile='custom'}));
$('measureBtn').onclick=measureNm;
$('openSeaMapBtn').onclick=()=>open('https://map.openseamap.org/','_blank');
$('openWindyBtn').onclick=()=>open('https://www.windy.com/-Waves-waves?waves,38.065,24.583,6','_blank');
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$(b.dataset.page).classList.add('active')});
$$('.subtab').forEach(b=>b.onclick=()=>{$$('.subtab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('#tripPage .drawer').forEach(d=>d.classList.remove('active'));$('trip-'+b.dataset.trip).classList.add('active')});
$('fab').onclick=()=>{let p=document.querySelector('.page.active').id, d=document.querySelector('#tripPage .drawer.active')?.id; if(p==='rentPage')$('newRentBtn').click(); else if(d==='trip-boats')$('newBoatBtn').click(); else if(d==='trip-destinations')$('newRouteBtn').click(); else toast('Διάλεξε προορισμό ή σκάφος για προσθήκη')};
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
async function initApp(){await loadDataJson(false,false);state=load();render()}
initApp();
